<?php

namespace Timelesstron\ObjectBuilder\Tests\ClassBuilder\Helper;

use DatePeriod;

class StockClass
{

    public function __construct(
        //todo diese müssen alle noch überprüft werden
        public readonly DatePeriod $DatePeriod,
        //        public readonly \ReflectionFunctionAbstract $ReflectionFunctionAbstract,
        //        public readonly \ReflectionFunction $ReflectionFunction,
        //        public readonly \ReflectionParameter $ReflectionParameter,
        //        public readonly \ReflectionType $ReflectionType,
        //        public readonly \ReflectionNamedType $ReflectionNamedType,
        //        public readonly \ReflectionUnionType $ReflectionUnionType,
        //        public readonly \ReflectionIntersectionType $ReflectionIntersectionType,
        //        public readonly \ReflectionMethod $ReflectionMethod,
        //        public readonly \ReflectionClass $ReflectionClass,
        //        public readonly \ReflectionObject $ReflectionObject,
        //        public readonly \ReflectionProperty $ReflectionProperty,
        //        public readonly \ReflectionClassConstant $ReflectionClassConstant,
        //        public readonly \ReflectionExtension $ReflectionExtension,
        //        public readonly \ReflectionZendExtension $ReflectionZendExtension,
        //        public readonly \ReflectionReference $ReflectionReference,
        //        public readonly \ReflectionAttribute $ReflectionAttribute,
        //        public readonly \ReflectionEnum $ReflectionEnum,
        //        public readonly \ReflectionEnumUnitCase $ReflectionEnumUnitCase,
        //        public readonly \ReflectionEnumBackedCase $ReflectionEnumBackedCase,
        //        public readonly \ReflectionFiber $ReflectionFiber,
        //        public readonly \RecursiveIteratorIterator $RecursiveIteratorIterator,
        //        public readonly \IteratorIterator $IteratorIterator,
        //        public readonly \FilterIterator $FilterIterator,
        //        public readonly \RecursiveFilterIterator $RecursiveFilterIterator,
        //        public readonly \CallbackFilterIterator $CallbackFilterIterator,
        //        public readonly \RecursiveCallbackFilterIterator $RecursiveCallbackFilterIterator,
        //        public readonly \ParentIterator $ParentIterator,
        //        public readonly \LimitIterator $LimitIterator,
        //        public readonly \CachingIterator $CachingIterator,
        //        public readonly \RecursiveCachingIterator $RecursiveCachingIterator,
        //        public readonly \NoRewindIterator $NoRewindIterator,
        //        public readonly \AppendIterator $AppendIterator,
        //        public readonly \InfiniteIterator $InfiniteIterator,
        //        public readonly \RegexIterator $RegexIterator,
        //        public readonly \RecursiveRegexIterator $RecursiveRegexIterator,
        //        public readonly \EmptyIterator $EmptyIterator,
        //        public readonly \RecursiveTreeIterator $RecursiveTreeIterator,
        //        public readonly \ArrayObject $ArrayObject,
        //        public readonly \ArrayIterator $ArrayIterator,
        //        public readonly \RecursiveArrayIterator $RecursiveArrayIterator,
        //        public readonly \SplFileInfo $SplFileInfo,
        //        public readonly \DirectoryIterator $DirectoryIterator,
        //        public readonly \FilesystemIterator $FilesystemIterator,
        //        public readonly \RecursiveDirectoryIterator $RecursiveDirectoryIterator,
        //        public readonly \GlobIterator $GlobIterator,
        //        public readonly \SplFileObject $SplFileObject,
        //        public readonly \SplTempFileObject $SplTempFileObject,
        //        public readonly \SplDoublyLinkedList $SplDoublyLinkedList,
        //        public readonly \SplQueue $SplQueue,
        //        public readonly \SplStack $SplStack,
        //        public readonly \SplHeap $SplHeap,
        //        public readonly \SplMinHeap $SplMinHeap,
        //        public readonly \SplMaxHeap $SplMaxHeap,
        //        public readonly \SplPriorityQueue $SplPriorityQueue,
        //        public readonly \SplFixedArray $SplFixedArray,
        //        public readonly \SplObjectStorage $SplObjectStorage,
        //        public readonly \MultipleIterator $MultipleIterator,
        //        public readonly \SessionHandler $SessionHandler,
        //        public readonly \__PHP_Incomplete_Class $__PHP_Incomplete_Class,
        //        public readonly \AssertionError $AssertionError,
        //        public readonly \php_user_filter $php_user_filter,
        //        public readonly \Directory $Directory,
        //        public readonly \PDOException $PDOException,
        //        public readonly \PDO $PDO,
        //        public readonly \PDOStatement $PDOStatement,
        //        public readonly \PDORow $PDORow,
        //        public readonly \CURLStringFile $CURLStringFile,
        //        public readonly \PharException $PharException,
        //        public readonly \Phar $Phar,
        //        public readonly \PharData $PharData,
        //        public readonly \PharFileInfo $PharFileInfo,
    ) {
    }

}
